project_id = "spuvedbcgsygzvloeyrs"

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false

[functions.admin-create-member]
verify_jwt = false

[functions.admin-revoke-member]
verify_jwt = false