// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spuvedbcgsygzvloeyrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdXZlZGJjZ3N5Z3p2bG9leXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NDYxNjAsImV4cCI6MjA4NjMyMjE2MH0.kBOBws-LOYamOrKdM63fknA_TjwCVGAl7tTpXN8uqBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});